from typing import Protocol
from gateway.models import CallSession

class VoiceHooks(Protocol):
    async def on_audio_chunk(self, session: CallSession, pcm: bytes) -> None: ...
    async def on_vad_start(self, session: CallSession) -> None: ...
    async def on_vad_end(self, session: CallSession) -> None: ...
    async def on_partial_transcript(self, session: CallSession, text: str) -> None: ...
    async def on_final_transcript(self, session: CallSession, text: str) -> None: ...

class AudioCounter:
    async def on_audio_chunk(self, session: CallSession, pcm: bytes) -> None:
        session.received_bytes += len(pcm)
